- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/logcache_tls?/private_key
  value: "((cc_logcache_tls.private_key))"

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/logcache_tls?/certificate
  value: "((cc_logcache_tls.certificate))"

- type: replace
  path: /instance_groups/name=api/jobs/name=cloud_controller_ng/properties/cc/logcache_tls?/ca_cert
  value: "((cc_logcache_tls.ca))"

- type: replace
  path: /variables/name=cc_logcache_tls?
  value:
    name: cc_logcache_tls
    type: certificate
    options:
      ca: log_cache_ca
      common_name: "api.((system_domain))"
      alternative_names:
      - "api.((system_domain))"
      - cloud-controller-ng.service.cf.internal
